### ISSUE TITLE
Alternative Input support

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#53]
From 4/13/21 Q2 planning meeting:

Investigate adding keyboard navigation for the 1.0 release.

Milestones:
start = 4/1/21
end = 5/15/21

Desig doc: [Fourier: Making Waves - Interactive Description Design](https://docs.google.com/document/d/1wOdmPMD704u4OLl9avI9tl2jpTvsAAcZwMaNfnr0qSs/edit?pli=1#heading=h.qbkcpoz1vzlo)

**Comment by pixelzoom** [comment]
4/9/21 Zoom discussion with @jbphet:

* Keyboard navigation mainly involves specify an order in which Nodes will be traversed. 

* It's unlikely that the default traversal order is what we will want. 
 
* Specifying traversal order involves creating an array of Nodes, where the order of the array determines the order in which Nodes will be traversed.

* Traversal order should be considered when making implementation decisions. Depending on the structure of the code, it may be easy or difficult to create the traversal array.  

4/12/21 Zoom discussion with @arouinfar:

* Some common UI components likely lack a11y design. For example, is traversal implemented for keypad?

* Sim-specific UI components will need an a11y design. For example, how should we treat an Amplitude slider + NumberDisplay?  As one component? As separate components? 

* Fourier is more than 1/2 way through implementation, and the code has been implemented with no consideration (or knowledge) of keyboard navigation requirements.  It's possible that big changes will be needed. 

* Are we too far along in the 1.0 release process to do this? 

* Let's discuss at design meeting.

**Comment by pixelzoom** [comment]
4/15/21 design meeting:

@kathy would like to proceed with:
* Include only interactive UI components in the traversal order
* Ignore the amplitude NumberDisplays and keypad

Start with the Discrete screen.

Wave Game is going to be a little challenging. Components from vegas (level selection, reward dialog,...) and will need to be instrumented.

Next steps:
* Specify the traversal order.  @arouinfar will create the associated design document and do a quick draft.  Then we'll have a sim-team design meeting to discuss.

**Comment by pixelzoom** [comment]
Add `supportsInteractiveDescription=true` to play around with what's already supported for keyboard navigation.

**Comment by pixelzoom** [comment]
I'm guessing (but not entirely certain) that we'll want to specify these options for the amplitude sliders.  Here they are, shown with their defaults as they appear in AccessibleValueHandler.js:

```
          // keyboard steps for various keys/interactions
          keyboardStep: ( rangeProperty.get().max - rangeProperty.get().min ) / 20,
          shiftKeyboardStep: ( rangeProperty.get().max - rangeProperty.get().min ) / 100,
          pageKeyboardStep: ( rangeProperty.get().max - rangeProperty.get().min ) / 10,
```

**Comment by pixelzoom** [comment]
Slack post to a11y channel:

Chris Malley  3:08 PM
Fourier: Making Waves will support keyboard navigation for the 1.0 release, see https://github.com/phetsims/fourier-making-waves/issues/53.  We had a design meeting last Thursday, and I have a rough idea of the desired traversal order. (@arouinfar will be doing a full spec.)  Can someone point me in the right direction for implementing this feature? Who to talk to, examples, documentation, etc. Thanks! (edited) 

Sam Reid  3:14 PM
I implemented limited keyboard support for Waves Intro in https://github.com/phetsims/wave-interference/issues/412, with help from @mjkauzmann
3:14
The first 2 commits took us a long way toward the goal:
3:15
https://github.com/phetsims/wave-interference/commit/b54e4ae0c22a0cdfd0f3894939033a71a236055a
3:15
https://github.com/phetsims/waves-intro/commit/b20a94ebce5dff0207b7992dee0d6ca515d68dcc

Michael Kauzmann  3:16 PM
I would say the best doc would be https://github.com/phetsims/phet-info/blob/master/doc/interactive-description-technical-guide.md, which alt input is a subset of interactive description. Most of everything down through the section "Add alternative-input input listeners" will be helpful, you can ignore stuff about "UtteranceQueue" and alerts. It will have you start by understanding the PDOM over in http://localhost:8080/scenery/doc/accessibility.html.

Chris Malley  3:17 PM
Thanks. Any exemplars that I should refer to? Or would that be Waves Intro? (edited) 

Michael Kauzmann  3:18 PM
Best/most recent alt input would probably be Molecules and Light, and Ratio and Proportion. I haven't looked at Waves Intro personally, but I bet it's got the goods too.

**Comment by pixelzoom** [comment]
We have missed the 5/15/21 milestone.

We are currently waiting for @arouinfar to produce the design document, and discuss how to handle the measurement tools with @terracoda.

**Comment by terracoda** [comment]
For the record, @arouinfar and @terracoda met on May 3rd, 2021.

I shared with @arouinfar why we have a two-step drag interaction for some draggable objects like the balloons in BASE, the Chemistry book in Friction, and the Bar Magnet in FL. And why we don't for the Both Hands interaction in Ratio and Proportion.

**Comment by pixelzoom** [comment]
Thanks for the update @terracoda. Can @terracoda or @arouinfar please summarize the "why" that you discussed?

**Comment by pixelzoom** [comment]
Thanks for the update @terracoda. Can @terracoda or @arouinfar please summarize what you discussed, and which interaction is appropriate for this sim?

**Comment by terracoda** [comment]
Sure, the balloon, book and magnet objects are the main interactions for the sim. If a learner cannot explore using that object, they cannot use the sim for anything useful.

Browser support for Web Standards has improved, and continue to do so, but when I design BASE, `aria-roledescription`, which is very useful for custom interactions, was not well-supported.

I had no ability as a designer to make the Yellow Balloon interaction sound interesting and intuitive to move as a straight-up custom interaction. When focused was moved to the balloon, screen reader users would hear something like this:

> Yellow Balloon, web application, grabbable, group with 2 items, Use W, A, S, and D keys to drag balloon.

Not fun, not engaging, not intuitive, not usable!

A button is a very intuitive interaction. Upon focus, hearing:

> Grab Yellow Balloon, button

is very intuitive. And once grabbed and in Application Mode, the user hears further instructions (appropriate to device platform) on how to move the balloon. 

This pattern works great for screen reader users, but doesn't work for visual keyboard users because the balloon does not look like a button. We then designed the visual hint to support visual keyboard users. The interaction is very intuitive for everyone once it is learned. It usually takes one go at it to learn it, so the hints go away until the sim reset.

**For Ratio and Proportion**
Two native HTML sliders precede the custom Both Hands interaction, and browser support for `aria-roledescription` is now good. Interviews with blind users showed us that blind users could easily operate Both Hands using the custom bi-manual input. No grab or activation button needed for the Both Hands interaction.

**The Rulers in CL and GFLB**
Note that in Coulomb's Law, our first sim with Alternative Input that was without Interactive Description, the ruler has no grab button. You can move it with the arrow keys on focus.

In Gravity Force Lab, however, which has Interactive Description, the ruler is s grab and drag interaction. This ruler, however, is not a primary interaction. We had to do extra work in the interactive description design to make screen users understand that it was not needed for productive exploration. The ruler's name in GFL is "Measure Distance Ruler" instead of "Grab Ruler". And the help text is, "If needed, grab ruler to measure distance between centers of spheres. Once grabbed, use keyboard shortcuts to move ruler." In this sim, the value for distance is provided through the Move m1 and Move m2 slider interactions. For non-visual users there is no specific need to grab the ruler. 

For Fourier Making Waves, @arouinfar and you will find the right balance. Reach out when/if you have questions.

**Comment by pixelzoom** [comment]
5/20/21 design meeting: @arouinfar @kathy-phet @pixelzoom 

@arouinfar is working on the doc here: https://docs.google.com/document/d/1wOdmPMD704u4OLl9avI9tl2jpTvsAAcZwMaNfnr0qSs/edit?pli=1#heading=h.qbkcpoz1vzlo

**Comment by arouinfar** [comment]
Thanks for the summary @terracoda! For now, I think it makes the most sense to skip the grab button. When it comes time to design the descriptions, we can reevaluate. 

@pixelzoom I updated the focus order in the linked table to include the erase button and the updated layout on the Game screen. 

We also need to specify step sizes for the sliders and NumberSpinners. I reviewed the mass controls in GFL (NumberControl) and GFLB (NumberPicker) for comparison. In GFL, the standard step size for alt input is not the same as `constrainValue` used on the slider. I've chosen to do the same here too, otherwise, it would take 60 key presses to traverse the entire slider range.

Amplitude sliders:
* Standard step (arrow keys): 0.1 
* Smaller step (shift + arrows): 0.01
* Bigger step (page up/down or fn up/down): 0.25

NumberSpinners:
* Bigger step (page up/down or fn up/down): 2

I don't know if NumberSpinner has support for a bigger step like NumberPicker. If it does, great. If not, I'm fine with deferring until we get to a sim with a NumberSpinner with a larger range.

**Comment by pixelzoom** [comment]
@arouinfar Can you please put this information in the design doc? https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-846284868

**Comment by pixelzoom** [comment]
@arouinfar I see this in the design doc, in the Focus Order column of _Table: Discrete Screen Outline_:

> _Each of the visible amplitude sliders_
> Amplitude {{#}}, slider
> Erase, button

I don't know how to interpret this. Please provide more description/clarification.

**Comment by pixelzoom** [comment]
@arouinfar Looking at other code that supports keyboard navigation, it looks like we need to decide what to connect to the "play area" vs "control panel".  For example, in greenhouse-effect MicroScreenView.js:

```js
    // PDOM - the accessible order for the control area contents
    this.pdomPlayAreaNode.pdomOrder = [ this.observationWindow, clipRectangle, windowFrameNode, photonEmissionControlPanel, moleculeControlPanel ];
    this.pdomControlAreaNode.pdomOrder = [ timeControlNode, showLightSpectrumButton, resetAllButton ];
```

I don't see this information specified in the design doc. 

Raising priority to high.

**Comment by pixelzoom** [comment]
@arouinfar I recall a discussion where we speculated that we could ignore "play area" vs "control panel" for now, because we're not doing interactive descriptions.   Well, each screen has 2 top-level Nodes, named `pdomPlayAreaNode` and `pdomControlAreaNode`.  And traveral order can only be set on those Nodes, not on the screen's ScreenView (top-level Node).   So I can either put everything under (e.g.) `pdomPlayAreaNode` for now, or we can take a stab at this now so we don't have to redo later. I recommend the latter.

**Comment by pixelzoom** [comment]
@jessegreenberg pointed out that we've been using "interactive description" incorrectly during this design process.  The definition is at https://github.com/phetsims/phet-info/blob/master/doc/interactive-description-technical-guide.md#what-does-interactive-description-mean, and it includes 3 components:
* State Description
* Responsive Description
* Alternative Input (including keyboard)

Relevant discussion with @jessegreenberg on Slack:

Chris Malley  4:32 PM
So in design meetings, we’ve been saying “Fourier will not support interactive description”.  What we should have been saying is “Fourier will not support state description and responsive description”.  Is that correct?

Jesse Greenberg  4:32 PM
Yep! That is correct.

Chris Malley  4:34 PM
Great, I understand now.  But I think the use of “description” in so many places is going to be a continual source of confusion.  Especially lumping alternative input into “description”.

Jesse Greenberg  4:40 PM
 But I think the use of “description” in so many places is going to be a continual source of confusion.
Heard, and agree that is a confusing aspect of the term. It has been brought up with the broader a11y team before and the decision was to continue using it since it is a good fit for the full feature set.

**Comment by pixelzoom** [comment]
With the exception of the measurement tools, the traversal order for the Discrete screen is implemented in the above commit.

**Comment by pixelzoom** [comment]
@arouinfar In Wave Game screen, where do you want the Info button in the traversal order? (appears on the level-selection UI))

**Comment by pixelzoom** [comment]
The traversal order for the Wave Game screen is implemented in the above 2 commits.

**Comment by pixelzoom** [comment]
TODO:

- [ ] support for measurement tools
- [ ] step options for spinners

**Comment by pixelzoom** [comment]
- [ ] Here's a problem to be solved:

1. Go to the Wave Game screen.
2. Tab to the Level 1 button, press spacebar. This animated to Level 1.
3. Press tab. Focus now goes to the navigation bar, instead of to the Back button in the status bar.

Investigate what's going on with TransitionNode, which handles the transition animation.

**Comment by pixelzoom** [comment]
Today's spring on traversal order went very well. Thanks @jessegreenberg for answering lots of questions on Slack.  There are still many things to be done for this issue (see checklist items above), but I'm confident that I can move on to implementation of the _Continuous_ screen.

**Comment by pixelzoom** [comment]
I'm going to rename this issue because we're doing more than "keyboard navigation" here. What we're actually doing is:
* specifiying traversal order, which is relevant for all forms of alternative input (including keyboard)
* implementing alternative input when an element has focus

**Comment by pixelzoom** [comment]
@arouinfar The amplitude step sizes that you've specified in https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-846284868 has a fundamental problem.  Users who are not using mouse/touch/keyboard will not be able to reach values that are increments of 0.05.  They will be restricted to 0.1 increments.  This may be OK for now, since keyboard is currently the primary form of input.  But it's not future-proof, and it doesn't serve all alterative-input users.   See https://github.com/phetsims/sun/issues/703#issuecomment-852325705 for more about this general issue.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-846284868, @arouinfar said:
> I don't know if NumberSpinner has support for a bigger step like NumberPicker. If it does, great. If not, I'm fine with deferring until we get to a sim with a NumberSpinner with a larger range.

The step API for NumberSpinner currently does not support bigger steps. And in general, it looks like that API needs work, see https://github.com/phetsims/sun/issues/704.   Since I'm going to skip this feature for Fourier.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-844311670, @terracoda said:
> Note that in Coulomb's Law, our first sim with Alternative Input that was without Interactive Description, the ruler has no grab button. You can move it with the arrow keys on focus.

In master, Coulomb's Law has been changed to use the grab-&-drag model.  So I can't use this as an example.

@jessegreenberg identified ProportionalDragHandle in area-model-common as a possible example. The general idea is to create a KeyboardDragListener and add it to the Node with addInputListener.  @jessegreenberg also said that I'll probably need to use options `tagName` and `focusable` of ParallelDOM for implementing traversal.

**Comment by pixelzoom** [comment]
- [ ] @arouinfar should this sim have a keyboard help dialog?

**Comment by pixelzoom** [comment]
Slack:
> Chris Malley  2:44 PM
> If a sim has alt input enabled, should it generally have a keyboard help dialog?
> 
> Jesse Greenberg  2:48 PM
> Yea, I think so. I don't think we have published a sim with alt input and not included a keyboard help dialog.

So I added general keyboard help to each screen, as shown below.

- [ ] @arouinfar should this sim have anything sim-specific in the keyboard help dialogs?  There is a dialog per screen.


<img width="505" alt="screenshot_1006" src="https://user-images.githubusercontent.com/3046552/120391598-81c25880-c2ec-11eb-8e04-df42fe97fe94.png">

**Comment by pixelzoom** [comment]
FYI... `supportsInteractiveDescription` is now enabled in package.json.  You don't need to use the query parameter.

**Comment by pixelzoom** [comment]
Removing "priority high" label, since I figured out how to avoid addressing "play area" and "control area'.   We may still want to visit that question, but it doesn't seem to be a hard requirement.

**Comment by pixelzoom** [comment]
Zoom design meeting @arouinfar and @pixelzoom 

* @arouinfar will make a first pass at splitting traversal into "play area" and "control area".  Even though we had considered not doing this for 1.0, the implementation of ScreenView makes it clear that the intent in to add Nodes to playArea or controlArea, and NOT to the ScreenView.  This is going to be tricky for Wave Game screen, related to https://github.com/phetsims/vegas/issues/90.

* Do UI comments need to have "accessible names" for Fourier 1.0 release?  Since the sim has pan-and-zoom, it might be more usable for low-vision users. (Looking at ResetAllButton, this seems to be done by passing a string via option `innerContent`.)  Let's ask @kathy-phet and the a11y team.

**Comment by pixelzoom** [comment]
> Do UI components need to have "accessible names" for Fourier 1.0 release? 

I discussed with @jessegreenberg on Zoom.  

accessibleName is the option to use.  innerContent is older style, and could be replaced by accessibleName. 

He doesn't feel like this would be a big win. The sim will not be promoted publically as having "labels only" (there's no icon for that).   For some things like eraser button and info button, it's not clear whether to "label" or "describe".

**Comment by terracoda** [comment]
Hmm, I feel there could be some big wins actually by adding accessibleName. That is, if the implementation time is not particularly heavy.

- Team win 1 - the team starts thinking about  accessible object names as they are designing the visual sim. I think this is actually a huge win. @arouinfar is already thinking about accessleNames for this sim.
- Team win 2 - devs get to understand more of the API options and if there are changes needed in the API for accessibleName
- Team win 3 - we all get to see the challenges in designing object names. It's not always obvious what to call something, as has already been pointed out. 
- Learner win - for sims that have sonification, adding accessibleNames adds meaning to the sounds for some users with vision impairments who might be using a screen reader.

**Comment by pixelzoom** [comment]
For 6/10/2021 design meeting, discuss the checklist items in these comments:

* https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-849985623
* https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-852328727
* https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-856099325
* https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-857136490

**Comment by pixelzoom** [comment]
6/10/21 Fourier design meeting: @arouinfar @kathy-phet @jessegreenberg @KatieWoe @pixelzoom

Notes and decisions were added to above checklist items, see "DECISION" comments.

Summary:
* In general, no work will be done on features related to screen reader for 1.0 release
* No accessibleNames for 1.0 release
* No play area and control area for 1.0 release
* Slider is working well enough for 1.0 release, additional work will be discussed by @kathy-phet and @jessegreenberg for Q3 goals

**Comment by pixelzoom** [comment]
Alternative input support is done for Discrete and Wave Game screens.

Remaining tasks for Continuous screen:

- [ ] Specify keyboard steps for sliders
- [ ] Specify pdomOrder (I'll start with "similar to Discrete screen")

**Comment by terracoda** [comment]
I am not sure if NumberDisplay is the same component as I've seen in the Arithmetic simulation, but I think it might be. I think it is an interface component that allows a learner to touch or click numbers in order to enter values into a textbox in the sim.

I agree if a learner can get to those discrete values right on the slider using the leyboard, they do not need to have access to the NumberDisplay. That just needs to be made clear in the Teacher Tips for the sim. Making that clear will help all learners. Mouse users might switch to using the keyboard when they need a precise number. I think of NumberDisplay as an accessibility feature for learners using mouse and touch who would otherwise have a hard time entering exact values.

In the future, should we want to make NumberDisplay available to other input methods, I think it would make sense that the component is a navigable region or group, that is thoughtfully designed to not exponentially increase the number of Tab stops in the PDOM.

**Comment by pixelzoom** [comment]
> I am not sure if NumberDisplay is the same component as I've seen in the Arithmetic simulation, but I think it might be. I think it is an interface component that allows a learner to touch or click numbers in order to enter values into a textbox in the sim.

NumberDisplay is a display only. It is not interactive.  In Fourier, I've added a mouse/touch listener (PressListener) that open a keypad.  There is currently no support for this in common-code, and it must be done on a sim-specific basic.  Adding keyboard support to open a keypad would involve more sim-specific work, as described in https://github.com/phetsims/fourier-making-waves/issues/53#issuecomment-857136490: 
> NumberDisplay does not support keyboard input. We’d probably need to identify as 'button', and add an onclick handler.

It would be useful to have a common-code subclass of NumberDisplay that adds support for opening a keypad.  But there is currently no proposal or GitHub issue for such a component.

**Comment by pixelzoom** [comment]
> I do not think that input support should be added to NumberDisplay - it is useful to have a UI component that is a display only, without the overhead of input handling. 

Thinking about this more... NumberDisplay is (or should be) used as a subcomponet on many other UI components: NumberControl, NumberSpinner,...    It would be nice to have keypad entry as an option for those controls.  And making keypad entry an option to NumberDisplay would make that easier.  Having to choose between NumberDisplay and (e.g.) InteractiveNumberDisplay  would be more complicated programmng, and make it more difficult to mutate this feature (turn if on and off), which is something that I suspect would be desirable via PhET-iO.

**Comment by pixelzoom** [comment]
I've converted all remaining checklist items to individual GitHub issues.

So this issue can be closed.
