### ISSUE TITLE
Items for Teacher Tips

### ISSUE THREAD

**Issue by arouinfar** [phetsims/fourier-making-waves#82]
Things to document in the Teacher Tips:

- [x] Harmonic vs. Component - #78 
  - [x] Clarify that the components in the Wave Packet screen are terms in the Fourier series
- [x] Game requires exact answers - #97 
- [x] Query parameter table: `gameLevels`, `rewardScore`, `screens`, `supportsPanAndZoom`, `audio` (values `enabled`, `disabled`, `muted`)
- [x] Components on the Wave Packet screen appear at fixed locations and their amplitudes change as the center or width of the wave packet changes. The distribution may appear skewed if the spacing between components is large, the standard deviation is small, or the center does not align with the component spacing.
- [x] Radians are dimensionless and omitted from the denominator for σ<sub>x</sub> and σ<sub>t</sub>. #105 
- [x] The y-axes on the Wave Packet screen are all auto-scaled and the min/max values are labelled on the Components and Sum graphs.
- [x] Sliders have interactive tick marks - #114 
- [x] Slider ranges are chosen to avoid undersampling that occurred in the Java version 
- [x] Infinite harmonics behavior

**Comment by pixelzoom** [comment]
- [ ] Discuss why we changed the ranges of controls in the Wave Packet screen, to avoid under-sampled states. See https://github.com/phetsims/fourier-making-waves/issues/158.  Might want to reference the Java version here.

**Comment by pixelzoom** [comment]
- [ ] Note that in the Wave Packet screen, the y-axis scale for the Amplitudes and Components charts may not always match.  If the Wave Packet Center is not aligned with a component wave number (as in the screenshot below) then the max component amplitude(s) will be less than the peak of the Continuous Waveform.

<img width="1017" alt="screenshot_1211" src="https://user-images.githubusercontent.com/3046552/130531295-a0095b3c-f2cf-4d87-841d-022da5830421.png">

**Comment by arouinfar** [comment]
Teacher Tips have been uploaded, closing.
