### ISSUE TITLE
Wave Packet screen features

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/fourier-making-waves#86]
This issue is a list of features to be implemented for the Wave Packet screen.  This is mainly for my benefit, but other team members can have a look to see which features of the Wave Packet screen have been completed. 

## Model
- [x] components (wave number & amplitude)
- [x] component spacing
- [x] wave packet: center
- [x] wave packet: standard deviation & conjugate
- [x] wave packet: width

## Amplitude chart
- [x] equation above chart (static)
- [x] x-axis label (dynamic)
- [x] x-axis tick marks (static)
- [x] y-axis label
- [x] y-axis grid lines
- [x] y-axis descriptions - see D2CAmplitudesChart.java `autoscaleY`
- [x] y-axis tick marks
- [x] y-axis autoscale
- [x] amplitude plots
- [x] infinite components plot (area under curve)
- [x] continuous waveform plot

## Components chart
- [x] expand/collapse button
- [x] equation above chart (dynamic)
- [x] x-axis label (dynamic)
- [x] x-axis grid lines
- [x] x-axis descriptions
- [x] x-axis zoom buttons
- [x] x-axis tick marks
- [x] y-axis label
- [x] y-axis descriptions, see https://github.com/phetsims/fourier-making-waves/issues/117
- [x] y-axis tick marks, see https://github.com/phetsims/fourier-making-waves/issues/117
- [x] y-axis autoscale, see https://github.com/phetsims/fourier-making-waves/issues/117
- [x] component plots
- [x] message: "An infinite number of components cannot be plotted."

## Sum chart
- [x] expand/collapse button
- [x] equation above chart (dynamic)
- [x] x-axis label (dynamic)
- [x] x-axis descriptions
- [x] x-axis grid lines
- [x] x-axis zoom buttons
- [x] x-axis tick marks
- [x] y-axis label
- [x] y-axis descriptions, see https://github.com/phetsims/fourier-making-waves/issues/117
- [x] y-axis tick marks, see https://github.com/phetsims/fourier-making-waves/issues/117
- [x] y-axis autoscale, see https://github.com/phetsims/fourier-making-waves/issues/117
- [x] sum plot - finite components
- [x] sum plot - infinite components
- [x] envelope plot - finite components
- [x] envelope plot - infinite components

## Miscellaneous
- [x] control panel
- [x] Reset All
- [x] width indicators
- [x] measurement tools (k<sub>1</sub>, ω<sub>1</sub>, λ<sub>1</sub>, T<sub>1</sub>) with support for infinite components

## Alt Input
- [x] slider keyboard steps
- [x] pdomOrder

**Comment by pixelzoom** [comment]
The Wave Packet screen is feature complete. I'll open a new GitHub issue to have it reviewed.
